"""initial sales os schema

Revision ID: 03b923e42ec4
Revises: 
Create Date: 2026-07-27 23:07:40.081590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b923e42ec4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_behavior', sa.Enum('EXCELLENT', 'GOOD', 'AVERAGE', 'POOR', 'UNKNOWN', name='payment_behavior_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_company_name'), 'customers', ['company_name'], unique=False)
    op.create_table('followup_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('quotation_number', sa.String(length=30), nullable=False),
    sa.Column('inquiry_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_company', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('followup_type', sa.Enum('REMINDER_1', 'REMINDER_2', 'REMINDER_3', 'VALIDITY_EXPIRY', 'OBJECTION_RESPONSE', 'NEGOTIATION_FOLLOWUP', name='followup_type_enum'), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'SENT', 'CUSTOMER_REPLIED', 'OBJECTION_DETECTED', 'NEGOTIATION_ACTIVE', 'CLOSED_WON', 'CLOSED_LOST', 'EXPIRED', name='followup_status_enum'), nullable=False),
    sa.Column('customer_reply', sa.Text(), nullable=True),
    sa.Column('reply_received_at', sa.DateTime(), nullable=True),
    sa.Column('objection_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followup_records_inquiry_id'), 'followup_records', ['inquiry_id'], unique=False)
    op.create_index(op.f('ix_followup_records_quotation_id'), 'followup_records', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_followup_records_quotation_number'), 'followup_records', ['quotation_number'], unique=False)
    op.create_table('handoff_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('handoff_id', sa.String(length=36), nullable=False),
    sa.Column('sales_order_id', sa.String(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('quotation_number', sa.String(length=30), nullable=False),
    sa.Column('buyer_company', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=5), nullable=False),
    sa.Column('job_reference', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('package_json', sa.Text(), nullable=False),
    sa.Column('notification_channel', sa.String(length=50), nullable=False),
    sa.Column('notification_recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoff_records_department'), 'handoff_records', ['department'], unique=False)
    op.create_index(op.f('ix_handoff_records_handoff_id'), 'handoff_records', ['handoff_id'], unique=False)
    op.create_index(op.f('ix_handoff_records_sales_order_id'), 'handoff_records', ['sales_order_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inquiry_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('EMAIL', 'WHATSAPP', 'WEB', 'INDIAMART', name='inquiry_source_enum'), nullable=False),
    sa.Column('sender_identifier', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('product_requested', sa.Text(), nullable=True),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('delivery_location', sa.String(length=255), nullable=True),
    sa.Column('delivery_date', sa.String(length=100), nullable=True),
    sa.Column('payment_expectation', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('AWAITING_INFO', 'NEW', 'WON', name='lead_status_enum'), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_inquiry_id'), 'leads', ['inquiry_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inquiry_id', sa.String(length=36), nullable=True),
    sa.Column('quotation_id', sa.String(length=36), nullable=True),
    sa.Column('quotation_number', sa.String(length=30), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('po_date', sa.String(length=50), nullable=True),
    sa.Column('buyer_company', sa.String(length=255), nullable=True),
    sa.Column('buyer_gstin', sa.String(length=20), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('price_per_unit_ex_gst', sa.Float(), nullable=True),
    sa.Column('gst_rate_pct', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount_inc_gst', sa.Float(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('delivery_date', sa.String(length=100), nullable=True),
    sa.Column('delivery_location', sa.String(length=255), nullable=True),
    sa.Column('special_conditions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mismatches_json', sa.JSON(), nullable=True),
    sa.Column('missing_critical_fields', sa.JSON(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('raw_po_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_inquiry_id'), 'purchase_orders', ['inquiry_id'], unique=False)
    op.create_table('quotation_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('quotation_number', sa.String(length=30), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('price_per_mt_ex_gst', sa.Float(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('subtotal_ex_gst', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('total_inc_gst', sa.Float(), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('negotiation_decision', sa.String(length=30), nullable=True),
    sa.Column('customer_offered_price', sa.Float(), nullable=True),
    sa.Column('draft_json', sa.Text(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_versions_quotation_id'), 'quotation_versions', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_quotation_versions_quotation_number'), 'quotation_versions', ['quotation_number'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_number', sa.String(length=30), nullable=False),
    sa.Column('inquiry_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SENT', 'REJECTED', name='quotation_workflow_status_enum'), nullable=False),
    sa.Column('buyer_company', sa.String(length=255), nullable=False),
    sa.Column('total_inc_gst', sa.Float(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('draft_json', sa.Text(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('sent_via', sa.String(length=50), nullable=True),
    sa.Column('sent_to', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_inquiry_id'), 'quotations', ['inquiry_id'], unique=False)
    op.create_index(op.f('ix_quotations_quotation_number'), 'quotations', ['quotation_number'], unique=True)
    op.create_table('sales_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inquiry_id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('po_id', sa.String(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('buyer_company', sa.String(length=255), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('delivery_date', sa.String(length=100), nullable=True),
    sa.Column('delivery_location', sa.String(length=255), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_orders_inquiry_id'), 'sales_orders', ['inquiry_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_po_id'), 'sales_orders', ['po_id'], unique=False)
    op.create_table('order_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=False),
    sa.Column('order_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DELIVERED', 'IN_TRANSIT', 'CANCELLED', 'PENDING', name='order_history_status_enum'), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_history_customer_id'), 'order_history', ['customer_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_customer_id'), 'payment_records', ['customer_id'], unique=False)
    op.create_table('quotation_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('quoted_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('WON', 'LOST', 'PENDING', 'EXPIRED', name='quotation_history_status_enum'), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_history_customer_id'), 'quotation_history', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_history_customer_id'), table_name='quotation_history')
    op.drop_table('quotation_history')
    op.drop_index(op.f('ix_payment_records_customer_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_order_history_customer_id'), table_name='order_history')
    op.drop_table('order_history')
    op.drop_index(op.f('ix_sales_orders_po_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_inquiry_id'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_quotations_quotation_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_inquiry_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_quotation_versions_quotation_number'), table_name='quotation_versions')
    op.drop_index(op.f('ix_quotation_versions_quotation_id'), table_name='quotation_versions')
    op.drop_table('quotation_versions')
    op.drop_index(op.f('ix_purchase_orders_inquiry_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_leads_inquiry_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_handoff_records_sales_order_id'), table_name='handoff_records')
    op.drop_index(op.f('ix_handoff_records_handoff_id'), table_name='handoff_records')
    op.drop_index(op.f('ix_handoff_records_department'), table_name='handoff_records')
    op.drop_table('handoff_records')
    op.drop_index(op.f('ix_followup_records_quotation_number'), table_name='followup_records')
    op.drop_index(op.f('ix_followup_records_quotation_id'), table_name='followup_records')
    op.drop_index(op.f('ix_followup_records_inquiry_id'), table_name='followup_records')
    op.drop_table('followup_records')
    op.drop_index(op.f('ix_customers_company_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
