SUPPORTED_SCOPES = {
    "crm:read",
    "customer:read",
    "customer_note:create",
    "lead:read",
    "pipeline:read",
    "approval:read",
    "inventory:read",
    "pricing_input:read",
    "task:read",
    "task:create",
    "activity:create",
    "followup:schedule",
    "quotation:prepare",
    "quotation:send",
    "discount:apply",
    "reminder:send",
    "negotiation:prepare",
    "negotiation:execute",
    "order:prepare",
    "order:accept",
    "handoff:dispatch",
    "message:send",
    "credit:change",
    "customer:merge",
    "deal:close",
}

# These capabilities are intentionally impossible to grant to Jarvis. Only a
# human admin can alter authority, approve exceptions, or destroy audit data.
FORBIDDEN_AI_SCOPES = {
    "authority:modify",
    "principal:modify",
    "approval:approve",
    "audit:delete",
}

DEFAULT_POLICIES = (
    {
        "action_type": "quotation_create",
        "name": "Create quotation",
        "decision_mode": "threshold_auto",
        "risk_level": "medium",
        "required_scope": "quotation:prepare",
        "approval_role": "finance_manager",
        "conditions": {"uses_business_quotation_and_margin_limits": True},
    },
    {
        "action_type": "discount_apply",
        "name": "Apply discount",
        "decision_mode": "threshold_auto",
        "risk_level": "medium",
        "required_scope": "discount:apply",
        "approval_role": "finance_manager",
        "conditions": {"uses_business_discount_and_margin_limits": True},
    },
    {
        "action_type": "credit_change",
        "name": "Change customer credit",
        "decision_mode": "approval_required",
        "risk_level": "high",
        "required_scope": "customer:read",
        "approval_role": "finance_manager",
        "conditions": {},
    },
    {
        "action_type": "customer_merge",
        "name": "Merge duplicate customers",
        "decision_mode": "approval_required",
        "risk_level": "high",
        "required_scope": "customer:read",
        "approval_role": "admin",
        "conditions": {},
    },
    {
        "action_type": "routine_reminder",
        "name": "Send routine reminder",
        "decision_mode": "auto_execute",
        "risk_level": "low",
        "required_scope": "reminder:send",
        "approval_role": None,
        "conditions": {"respect_daily_outbound_limit": True},
    },
    {
        "action_type": "negotiation_response",
        "name": "Respond to negotiation",
        "decision_mode": "prepare_only",
        "risk_level": "high",
        "required_scope": "negotiation:prepare",
        "approval_role": "sales_manager",
        "conditions": {},
    },
    {
        "action_type": "order_accept",
        "name": "Accept purchase order",
        "decision_mode": "approval_required",
        "risk_level": "high",
        "required_scope": "order:accept",
        "approval_role": "sales_manager",
        "conditions": {},
    },
    {
        "action_type": "add_customer_note",
        "name": "Add customer note",
        "decision_mode": "auto_execute",
        "risk_level": "low",
        "required_scope": "customer_note:create",
        "approval_role": None,
        "conditions": {},
    },
    {
        "action_type": "create_task",
        "name": "Create CRM task",
        "decision_mode": "auto_execute",
        "risk_level": "low",
        "required_scope": "task:create",
        "approval_role": None,
        "conditions": {},
    },
    {
        "action_type": "record_activity",
        "name": "Record CRM activity",
        "decision_mode": "auto_execute",
        "risk_level": "low",
        "required_scope": "activity:create",
        "approval_role": None,
        "conditions": {},
    },
    {
        "action_type": "schedule_followup",
        "name": "Schedule quotation follow-up",
        "decision_mode": "auto_execute",
        "risk_level": "low",
        "required_scope": "followup:schedule",
        "approval_role": None,
        "conditions": {},
    },
    {
        "action_type": "prepare_quotation",
        "name": "Prepare quotation draft",
        "decision_mode": "prepare_only",
        "risk_level": "medium",
        "required_scope": "quotation:prepare",
        "approval_role": "finance_manager",
        "conditions": {"dispatch_prohibited": True},
    },
    {
        "action_type": "message_send",
        "name": "Send customer message",
        "decision_mode": "threshold_auto",
        "risk_level": "medium",
        "required_scope": "message:send",
        "approval_role": "sales_manager",
        "conditions": {"respect_consent_and_daily_limit": True},
    },
    {
        "action_type": "quotation_send",
        "name": "Send quotation",
        "decision_mode": "threshold_auto",
        "risk_level": "high",
        "required_scope": "quotation:send",
        "approval_role": "finance_manager",
        "conditions": {"requires_complete_pricing": True},
    },
    {
        "action_type": "po_validate",
        "name": "Validate purchase order",
        "decision_mode": "auto_execute",
        "risk_level": "medium",
        "required_scope": "order:prepare",
        "approval_role": "production_manager",
        "conditions": {"deterministic_validation_only": True},
    },
    {
        "action_type": "po_accept",
        "name": "Accept purchase order",
        "decision_mode": "threshold_auto",
        "risk_level": "high",
        "required_scope": "order:accept",
        "approval_role": "production_manager",
        "conditions": {"requires_revalidation": True},
    },
    {
        "action_type": "sales_order_create",
        "name": "Create sales order",
        "decision_mode": "threshold_auto",
        "risk_level": "high",
        "required_scope": "order:accept",
        "approval_role": "production_manager",
        "conditions": {"requires_valid_po_and_fulfillment_allocation": True},
    },
    {
        "action_type": "deal_close_won",
        "name": "Close deal as won",
        "decision_mode": "threshold_auto",
        "risk_level": "high",
        "required_scope": "deal:close",
        "approval_role": "sales_manager",
        "conditions": {"requires_valid_order_acceptance": True},
    },
    {
        "action_type": "deal_close_lost",
        "name": "Close deal as lost",
        "decision_mode": "approval_required",
        "risk_level": "medium",
        "required_scope": "deal:close",
        "approval_role": "sales_manager",
        "conditions": {"requires_reason": True},
    },
)
